### ISSUE TITLE
cli test yaml delegator server requires `DELEGATOR_FEEPAYER_PK` & `TEST_DELEGATOR_REPORTER_PK` env variables

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1000]
currently delegator tx testing is skipped since it's not available

**Comment by nick-bisonai** [comment]
it doesn't work just by adding env, but also requires initialization from delegator sign service `sign.service.spec.ts`
```
await service.initialize({ feePayerPrivateKey: process.env.DELEGATOR_FEEPAYER_PK })
```

**Comment by martinkersner** [comment]
@nick-bisonai Is this issue still relevant after the migration to go delegator?

**Comment by nick-bisonai** [comment]
i don't think so, will close
