### ISSUE TITLE
track feedRouter and feedProxy latestRoundData() call count for business statistics

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1044]
add data to orakl-grafana business board

**Comment by Intizar-T** [comment]
relevant discussions:
https://bisonai.slack.com/archives/C04772WQ3DW/p1720768650256659
https://www.notion.so/bisonai/3-3-Information-of-Orakl-Network-4782925a67ac43f0a21bac0102d8297e?pvs=4

**Comment by nick-bisonai** [comment]
it has already been discussed and being planned from kaiascan team
