### ISSUE TITLE
[Monitoring] Negative submission time report

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1052]
From time to time, we receive an alert claiming that we did not submit -T minutes.

## Questions to answer
* Why is it happening?
* Is it actual warning?

## TODO
* Fix the computation of time delay.

![Image](https://github.com/Bisonai/orakl/assets/2312761/84a44010-e412-4957-8fd3-ab0b7ece3195)

**Comment by nick-bisonai** [comment]
planned to use different code base for monitoring
