### ISSUE TITLE
[Monitoring] Alert on non-Bisonai node down

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1054]

**Comment by nick-bisonai** [comment]
This can be closed since we have peer count check and health check

if peer count decrease and healthcheck doesn't say anything, that'd mean non-bisonai node is down
ex)
non-bisonai node down
```
number of peers in orakl offchain cluster has decreased from 2 to 1
```

bisonai node down
```
orakl-node is down
```
