### ISSUE TITLE
daily checklist script

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1060]
1. call vrf
2. call rr
3. call df
4. query latest 1000 submissions for each datafeeds 

> compare the latest timestamp with current timestamp (should not be that much diff)
> ~~check for failed submissions~~ (graph-node doesn't support error handler, nor events are emitted for failed cases)
> check timestamp gaps (less than 20-25 secs)

**Comment by nick-bisonai** [comment]
- for submission information, grafana dashboard currently only shows last submission time offset, which is good to see current status at that moment, but doesn't show average submission frequency for certain amount of time. so this kind of checks could be meaningful

**Comment by nick-bisonai** [comment]
if using github action schedule trigger, it could be automated
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by martinkersner** [comment]
> * for submission information, grafana dashboard currently only shows last submission time offset, which is good to see current status at that moment, but doesn't show average submission frequency for certain amount of time. so this kind of checks could be meaningful

If we need to see a stats for longer periods, we can add it to dashboard as well.

**Comment by martinkersner** [comment]
Please consider this together with https://github.com/Bisonai/orakl-monitor, https://github.com/bisonai/bisontry and https://github.com/Bisonai/orakl/tree/master/monitor 🙏

**Comment by martinkersner** [comment]
@nick-bisonai Let's close this down and reopen for data feed only if you think it is necessary.
