### ISSUE TITLE
use pnpm for package management

### ISSUE THREAD

**Issue by KelvinThai** [Bisonai/orakl#1101]
compared to yarn, it's said that `pnpm` is overall faster and uses less disk space.
making package installation or commands faster could help

https://pnpm.io/motivation

(seems better to apply after checking monorepo implement worked out without errors)

**Comment by KelvinThai** [comment]
Can we close this issue? I believe it's done @nick-bisonai

**Comment by nick-bisonai** [comment]
it's not done but it can be closed. 
it was just a suggestion not a hanging technical debt

**Comment by nick-bisonai** [comment]
not relevant anymore.
