### ISSUE TITLE
Delete old baobab DB

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1136]
- [ ] Delete deprecated Bobaob DB
- [ ] Rename the new DB to previous name

**Comment by martinkersner** [comment]
@dev4jaehunkim Before deleting baobab DB, we should fix this first https://github.com/Bisonai/orakl/issues/1139

**Comment by jay-kim-kor** [comment]
@martinkersner We can't change DB instance name after created. Should I write name to another style when I created new DB in Cypress?

**Comment by martinkersner** [comment]
@jay-kim-kor  That is unfortunate. Let's have some name closer to the original one. Maybe something like `orakl-cypress-prod-db-${DATE}`
