### ISSUE TITLE
reducer js taking `PATH` and `PARSE` for same reducer functionality.

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1165]
should be fixed to one command

**Comment by martinkersner** [comment]
@Bisonai/orakl-team The new version of Orakl Network Reducer does not accept `PATH` function, only `PARSE` is supported. Closing down.

https://github.com/Bisonai/orakl/blob/6b33b7294a5348b17bd030d468952af4c34aa665/node/pkg/utils/reducer/reducer.go#L43-L63
