### ISSUE TITLE
Cost for `Cloud Monitoring` increased from $0 on Feb 14

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1186]

**Comment by jay-kim-kor** [comment]
I have a question to clarify. For my understand, it does means `Investigate why increase from $0 after Feb 14`. Am I understand exactly?

If not, could you explain about it please?

**Comment by martinkersner** [comment]
> I have a question to clarify. For my understand, it does means `Investigate why increase from $0 after Feb 14`. Am I understand exactly?
> 
> If not, could you explain about it please?

Yes!

**Comment by martinkersner** [comment]
On February 29, `Cloud monitoring` costs disappeared 🤔
