### ISSUE TITLE
Update outdated actions in `orakl-grafana` CI/CD

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1253]
![Image](https://github.com/Bisonai/orakl/assets/2312761/40babda6-288e-4db8-8f3b-79486cf11c7e)

https://github.com/Bisonai/orakl-grafana/actions/runs/8275510888

**Comment by nick-bisonai** [comment]
fixed from https://github.com/Bisonai/orakl-grafana/pull/30
