### ISSUE TITLE
Use validator for aggregator on-chain check

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#137]

**Comment by KelvinThai** [comment]
I think we can close this since we're moving towards offchian aggregation

**Comment by martinkersner** [comment]
Yes, but the feature has to be remove from `Aggregator` contract.

**Comment by KelvinThai** [comment]
linked issue: https://github.com/Bisonai/orakl/issues/1097

**Comment by KelvinThai** [comment]
we will remove validator for onchain validation

**Comment by martinkersner** [comment]
@Bisonai/orakl-team Orakl Network v0.2 does not include on-chain aggregator check. Closing down the issue.
