### ISSUE TITLE
Ideas for deviation check

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1428]
We have 3 possible ideas for check the deviation threshold on fetcher for each reporter for each aggregator. 

1. Compare current submission with local aggregated value
      - This is current solution which we use on fetcher - https://github.com/Bisonai/orakl/blob/master/fetcher/src/job/job.utils.ts#L236-L258
      - Disadvantage of approach is the data will be comparing the current submission with already aggregated value as a part latest fetching round, where the data is 2 seconds old.  So, theoretically it will work when there is huge jump between the 2 secs interval, but we not the value of the latest submission, where it means it will be incorrect solution. 

2. Compare current submission with latest aggregated value from on-chain contract
    - The solution is very similar to PoR's deviation check where we compare current aggregated data with `latestRounds` on-chain aggregated value. 
    - Reporter doesn't know exact submission it made on latest round, and it is not possible to read the latest submission data since we clean up the previous rounds information from on-chain data.
   - Implementation of the idea: https://github.com/Bisonai/orakl/pull/975

3. Latest submission data extracted from graphnode

4. Store each submission on db with making simple table to store latest submission data for each aggregator
    - Similar approach could be applied on this solution.  
    - https://github.com/Bisonai/orakl/pull/847

**Comment by nick-bisonai** [comment]
no more relevent regarding off-chain aggregation codes
