### ISSUE TITLE
check if value has changed in local aggregates before updating

### ISSUE THREAD

**Issue by Intizar-T** [Bisonai/orakl#1729]
Current implementation sends local aggregate to db at a given interval. Update that logic to check if the computed local aggregate is different than the previous one. If not changed then don't make a db transaction. However, there should be an interval after which local aggregates should be written to db even if the value doesn't change.

https://github.com/Bisonai/orakl/blob/a95bf34cfc83a776338cf12aba10095322066612/node/pkg/fetcher/collector.go#L126

**Comment by nick-bisonai** [comment]
will be closed since it is not planned to be implemented. will reopen if required
