### ISSUE TITLE
(OraklNode) Seperate Reporter from the service

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1777]
reporter can now consume dal api to get submission info

**Comment by Intizar-T** [comment]
1. Stop Aggregator from storing latestGlobalAggregate in `redis` (store only on `pgsql` for monitoring purposes)
2. Move reporter implementations referenced from DAL to DAL service
3. From reporter, call DAL to get latest submission
4. Implement separate entrypoint for Reporter (make it a standalone service):
     -  cmd
     - dockerfile
     - helmchart

![20240715_155021](https://github.com/user-attachments/assets/5ad365a9-a29e-4d7d-b669-06d54e796fa8)

**Comment by nick-bisonai** [comment]
done
