### ISSUE TITLE
`gasAfterPaymentCalculation` is too high

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#221]
https://www.notion.so/krustuniverse/Gas-Estimation-d7ca3d6676964d4d821ad38892aeb3c7

**Comment by KelvinThai** [comment]
I think the calculation is quite precise, as compared to fulfillment on baobab. It cost: 108,478 (we did some extra calculation in the fulfill functions.)
ref: fulfilment transaction: https://baobab.scope.klaytn.com/tx/0xb5ec55bb4e2a27e7f3f3348916e5b1f9ed22d3112b0f4b7c7b10d47bc072bc41?tabId=internalTx

**Comment by martinkersner** [comment]
@KelvinThai Yes, the calculation should be precise, but the main point of this issue is that it is 3x larger than with Chainlink. That is quite significant difference! I am suspecting we do something quite unoptimized and wanted to know what it is and if we can improve it.

**Comment by KelvinThai** [comment]
I think the number is outdated. I tried chainlink on bsc testnet and the gas used for fulfillment is 188,297 which is somewhere similar to ours.
ref: https://testnet.bscscan.com/tx/0x948c53e0a133783ae5397c9806477bb7c5611bb189ef104f863ed5272eb033f8

**Comment by martinkersner** [comment]
I am not fully convinced. At https://vrf.chain.link/, there is a link to `VRFCoordinator` (https://sepolia.etherscan.io/address/0x8103b0a8a00be2ddc778e6e7eaa21791cd364625#readContract) which allows to query config through `getConfig` and it returns the following response

```
minimumRequestConfirmations   uint16 :  3
maxGasLimit   uint32 :  2500000
stalenessSeconds   uint32 :  86400
gasAfterPaymentCalculation   uint32 :  33285
```

**Comment by martinkersner** [comment]
We changed quite many things related to gas after payment calculation for VRF and RR. The description above are outdated and does not correspond to the latest code. Will raise the issue again if we encounter it again.
