### ISSUE TITLE
Don't allow to request for VRF with prepayment unless there is sufficient balance

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#308]
Recently, we had problem that it was possible to request VRF through prepayment, but during fulfillment inside of `chargeFee` transaction failed because of low account balance. This should never happen.

**Comment by KelvinThai** [comment]
We have this function already. We did not set the MinBalance value so it was 0 by default. I set it to 0,1 and it works. Consumers can not request if the balance is under 0,1 Klay in prepayment.

**Comment by martinkersner** [comment]
@KelvinThai Please update the deployment script to include it. https://github.com/Bisonai/orakl/blob/master/contracts/deploy/2-VRFCoordinator.ts

**Comment by martinkersner** [comment]
@KelvinThai We also need to add it to RequestResponseCoordinator deployment script https://github.com/Bisonai/orakl/blob/master/contracts/deploy/1-RequestResponseCoordinator.ts

**Comment by KelvinThai** [comment]
OK. will do!
