### ISSUE TITLE
End to end investigation for VRF, RR not being fulfiled

### ISSUE THREAD

**Issue by KelvinThai** [Bisonai/orakl#317]
Identify the root cause for all unfulfilled requests

**Comment by KelvinThai** [comment]
related issues: https://github.com/Bisonai/orakl/issues/318 https://github.com/Bisonai/orakl/issues/315

**Comment by martinkersner** [comment]
@KelvinThai Can we close this one?

**Comment by KelvinThai** [comment]
Yes, I think we can close it now. I will raise new issues if I find anything
