### ISSUE TITLE
update configs, document for new VRF, RR contracts

### ISSUE THREAD

**Issue by KelvinThai** [Bisonai/orakl#327]
related repos:
https://github.com/Bisonai/request-response-consumer
https://github.com/Bisonai/vrf-consumer

**Comment by martinkersner** [comment]
@KelvinThai What are you planning to add there exactly?

**Comment by KelvinThai** [comment]
Just update the new contracts addresses in hardhat config and consumer docs.

**Comment by KelvinThai** [comment]
I raised the pr in vrf and rr consumer repo
https://github.com/Bisonai/vrf-consumer/pull/10 
https://github.com/Bisonai/request-response-consumer/pull/8
