### ISSUE TITLE
Github actions publish fails

### ISSUE THREAD

**Issue by bayram98** [Bisonai/orakl#330]
When publishing new contract package from github actions, `run yarn publish` fails, but still managed to publish to npm. 
   
https://github.com/Bisonai/orakl/actions/runs/4319523683/jobs/7538804107
https://github.com/Bisonai/orakl/actions/runs/4122183219/jobs/7118656444

**Comment by jay-bisonai** [comment]
@martinkersner I check those links to job and it seems like deprecated(can't found workflows that made job). So, I closed this issue because I think we already migrate to new workflow for contracts.
