### ISSUE TITLE
Slither + Mythril

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#345]

**Comment by KelvinThai** [comment]
The result can be found here: https://www.notion.so/bisonai/SM-security-audit-with-slither-and-Mythril-6fadd8c2459a47449fdf2a053dced1d9

**Comment by martinkersner** [comment]
@KelvinThai I am going to close this as completed okay? We have created a separate issues for each finding and later we can go through this together.

**Comment by KelvinThai** [comment]
let's reopen this issue. I'll dive deeper, solve all the reds and yellows, If that's not the problem, I'll explain to the auditors we've alr acknowledge all automated tests through an official document

**Comment by martinkersner** [comment]
@KelvinThai Let's focus on this next week if we accomplish everything on the application side.

**Comment by martinkersner** [comment]
@KelvinThai Closing :)
