### ISSUE TITLE
Test KlaytnFinder for source code verification

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#371]

**Comment by KelvinThai** [comment]
KlaytnFinder is nowhere better than klayscope. Still no verification API, no custom error return. At least it states at the beginning that we need to flatten the code before submitting and verifying.
let's stick with klayscope for now.


![Image](https://user-images.githubusercontent.com/54656638/224941501-a7e40b2b-88f7-4436-b357-a3b6a9d0b343.png)

**Comment by martinkersner** [comment]
@KelvinThai Thank you! We could implement this feature internally, after we take over the Klaytn Finder from April.

cc @haminprk @bryan-bisonai
