### ISSUE TITLE
Optimize gas fee for deregisterProvingKey in VRFCoordinator contract

### ISSUE THREAD

**Issue by huyhuynh3103** [Bisonai/orakl#399]

**Comment by martinkersner** [comment]
Hello @HuyHuynh3103 ,

Thank you for raising the issue! Could you be please more specific where is the exact problem?

We have noticed the same issue in chainlink smart contract and proposed a fix through https://github.com/smartcontractkit/chainlink/pull/8248.

According to our understanding our implementation does not have this problem.  We have added a `break` https://github.com/Bisonai/orakl/blob/22835218e78f78aacb38c255b61f1644853d5fcd/contracts/src/v0.1/VRFCoordinator.sol#L171 to save a gas in `deregisterProvingKey`.

Cheers,
Martin

**Comment by HuyHuynh3103** [comment]
Hello @martinkersner, 
I can save gas for deregisterProvingKeyHashes function by caching the length of array to memory, avoiding assigning defaults value for the index variable, and unchecking the overflow of the looping index while increasing its value. 
I can not create a new development branch while creating an issue as well as pushing my changes from local branch. So I fork this project and create pull request into its forked repo. Here is pull request: https://github.com/Bisonai/orakl/pull/401.

**Comment by martinkersner** [comment]
Thank you! Please check my comment at https://github.com/Bisonai/orakl/pull/401
