### ISSUE TITLE
`maxGasLimit` (VRF, Request-Response)

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#44]
`orakl/contracts/config/localhost/vrf.json`

```
{
    "maxGasLimit": 1000000,
    "gasAfterPaymentCalculation": 90692,
    "feeConfig": {
        "fulfillmentFlatFeeKlayPPMTier1": 0,
        "fulfillmentFlatFeeKlayPPMTier2": 0,
        "fulfillmentFlatFeeKlayPPMTier3": 0,
        "fulfillmentFlatFeeKlayPPMTier4": 0,
        "fulfillmentFlatFeeKlayPPMTier5": 0,
        "reqsForTier2": 0,
        "reqsForTier3": 0,
        "reqsForTier4": 0,
        "reqsForTier5": 0
    },
    "directPaymentConfig": {
        "fulfillmentFee": "250000000000000000",
        "baseFee": "500000000000000000"
    },
    "oracle": [
        {
            "address": "0xdD2FD4581271e230360230F9337D5c0430Bf44C0",
            "publicProvingKey": [
                "95162740466861161360090244754314042169116280320223422208903791243647772670481",
                "53113177277038648369733569993581365384831203706597936686768754351087979105423"
            ]
        }
    ]
}
```

**Comment by KelvinThai** [comment]
This parameter set the upper bound for `callbackGasLimit` 
```
if (callbackGasLimit > s_config.maxGasLimit) {
            revert GasLimitTooBig(callbackGasLimit, s_config.maxGasLimit);
        }
```

This is also a very ETH 1.0-specific parameter where the gas price changes a lot. Users must be cautious about what to implement in the fulfill function. This does not have much meaning in Klaytn where the gas price stays low and there is no miner to pick high gas Txs. The default 1000000 is more than enough for fulfillment and is usable in this case. We are able to set it to another value anyway.

**Comment by martinkersner** [comment]
@KelvinThai Thank you for the analysis! The price of gas can also fluctuate in Klaytn though. Do you propose to keep 1M `maxGasLimit`?

**Comment by KelvinThai** [comment]
How about we keep this at 2500000, just like chainlink is using on BSC and ETH. We can adjust it later based on real-word conditions.
