### ISSUE TITLE
Allow other data type requests other than `uint256`

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#455]
https://docs.chain.link/any-api/get-request/examples/single-word-response/#response-types

- uint256 - Unsigned integers
- int256 - Signed integers
- bool - True or False values
- string - String
- bytes32 - Strings and byte values. If you need to return a string, use bytes32. Here’s [one method](https://gist.github.com/alexroan/a8caf258218f4065894ecd8926de39e7) of converting bytes32 to string. Currently, any return value must fit within 32 bytes. If the value is bigger than that, make multiple requests.
- bytes - Arbitrary-length raw byte data

**Comment by martinkersner** [comment]
And later let's focus on this https://docs.chain.link/any-api/introduction#requesting-off-chain-data

**Comment by KelvinThai** [comment]
The way chainlink supports multiple data types is as follows:
1. In the request function, the consumer specifies the contract address + callback function + job_ID. They need to reference JobID carefully to make sure the job returns the correct data and type.
2. The consumer implements the callback functions. They can name it whatever they want, doesn't have to be named `fullfill()`.
3. The consumers make the request, offchain oracles perform operations based on Job_id to make sure it retrieves the correct data and type.
4. offchains oracle calls the callback function and completes the circle.
This way the solution is very scalable. Consumers need to understand Job_id before implementation. In case we want new types, we just need to add more IDs. But this makes a lot of changes in our current implementations.
We can go the easy way: multiple fullfill functions for multiple data types, but we can not add more after the smart contacts is deployed.

**Comment by martinkersner** [comment]
@KelvinThai Thank you for the research!

1. In the current version of Request-Response, we already have a notion of `jobId` (https://orakl-network.gitbook.io/docs/developers-guide/request-response#request-and-response-post-processing) which specifies a data type that is expected to be received. It is probably good to continue in this, same as Chainlink is doing. There are not many data types which we have to support (listed in the description of this issue) which is good for us because once we have an implementation for each of them we do not have to worry we might suddenly have to support some new one.

2. I would prefer to stick with a single name (`fulfill()`) so we do not have to transfer additional value to off-chain oracle for it to know where it should respond. However, I guess it is not possible to inherit from abstract contract (`RequestResponseConsumerBase`) without overriding all virtual functions similar to the one below. https://github.com/Bisonai/orakl/blob/402b40dc75513cb977b426cff72cc29d9ba0353b/contracts/src/v0.1/RequestResponseConsumerBase.sol#L28
If that is true, then we will have to also pass the function selector when request for data from off-chain. We would still need to create multiple `rawFulfillDataRequest` functions. I guess Chainlink does not have similar function and forces users to make this check by themselves. We have added it there for a consumer convenience.
https://github.com/Bisonai/orakl/blob/402b40dc75513cb977b426cff72cc29d9ba0353b/contracts/src/v0.1/RequestResponseConsumerBase.sol#L30-L36

3. This was the plan.
4. We can make sure we support all data types, and not worry about something missing. We will have to create multiple `fulfillDataRequest()` functions for each supported data type.
https://github.com/Bisonai/orakl/blob/402b40dc75513cb977b426cff72cc29d9ba0353b/contracts/src/v0.1/RequestResponseCoordinator.sol#L352-L418
It could look something as below. We would have multiple `fulfillDataRequest` functions with different `response` data type.
```Solidity
function validateDataResponse(
    RequestCommitment memory rc,
    uint256 requestId
) internal returns(bool) {
    if (!sOracles[msg.sender]) {
        revert UnregisteredOracleFulfillment(msg.sender);
    }

    bytes32 commitment = sRequestCommitments[requestId];
    if (commitment == 0) {
        revert NoCorrespondingRequest();
    }

    if (
        commitment !=
        keccak256(abi.encode(requestId, rc.blockNum, rc.accId, rc.callbackGasLimit, rc.sender))
    ) {
        revert IncorrectCommitment();
    }

    delete sRequestCommitments[requestId];

    return true;
}

function fulfill(bytes memory resp, RequestCommitment memory rc) internal {
    // Call with explicitly the amount of callback gas requested
    // Important to not let them exhaust the gas budget and avoid oracle payment.
    // Do not allow any non-view/non-pure coordinator functions to be called
    // during the consumers callback code via reentrancyLock.
    // Note that callWithExactGas will revert if we do not have sufficient gas
    // to give the callee their requested amount.
    s_config.reentrancyLock = true;
    bool success = callWithExactGas(rc.callbackGasLimit, rc.sender, resp);
    s_config.reentrancyLock = false;
}

function pay(RequestCommitment memory rc, bool isDirectPayment, uint256 startGas) internal returns (uint256 payment) {
    // We want to charge users exactly for how much gas they use in their callback.
    // The gasAfterPaymentCalculation is meant to cover these additional operations where we
    // decrement the account balance and increment the oracles withdrawable balance.
    // We also add the flat KLAY fee to the payment amount.
    // Its specified in millionths of KLAY, if s_config.fulfillmentFlatFeeKlayPPM = 1
    // 1 KLAY / 1e6 = 1e18 pebs / 1e6 = 1e12 pebs.
    (uint256 balance, uint64 reqCount, , ) = sPrepayment.getAccount(rc.accId);

    if (isDirectPayment) {
        payment = balance;
    } else {
        payment = calculatePaymentAmount(
            startGas,
            sConfig.gasAfterPaymentCalculation,
            getFeeTier(reqCount)
        );
    }

    sPrepayment.chargeFee(rc.accId, payment, msg.sender);

    return payment;
}

function fulfillDataRequest(
    uint256 requestId,
    uint256 response,
    RequestCommitment memory rc,
    bool isDirectPayment
) external nonReentrant returns (uint256) {
    uint256 startGas = gasleft();
    validateDataResponse(rc, requestId);
    RequestResponseConsumerBase rr;
    bytes memory resp = abi.encodeWithSelector(
        sFulfillFunctionSelector[reqestId],
        requestId,
        response
    );
    fulfill(resp, rc);
    (uint256 payment, bool success) = pay(rc, isDirectPayment, startGas);
    emit DataRequestFulfilledUint256(requestId, response, payment, success);
    return payment;
}
```
