### ISSUE TITLE
orak-cli internal server error with aggregator remove --id

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#459]
When I execute 
'yarn cli aggregator remove --id {num}`
this shows simply internal server error.

Actual error is because foreign key constraint 'Data'
It means already collected data and saved in Data colume using foreign key of aggregator can not simply delete the aggregator.

Or deletion should be following order
delete from data where aggregator_id = 1;
delete from aggregates where aggregator_id = 1;
delete from aggregators where aggregator_id = 1; 

If create Data column with ON DELETE CASCADE, then it will work.

Query 1 ERROR: ERROR:  update or delete on table "aggregators" violates foreign key constraint "data_aggregator_id_fkey" on table "data"
DETAIL:  Key (aggregator_id)=(1) is still referenced from table "data".

**Comment by martinkersner** [comment]
@joseph-bisonai What did you expect to happen when you called this command? Did you want to just "remove" the aggregator so you don't see it or you wanted to delete all the data associated with it?

**Comment by joseph-bisonai** [comment]
@martinkersner eventually it should remove all related data I think

**Comment by martinkersner** [comment]
Okay! We can set it up like that!
