### ISSUE TITLE
The last active item in the state will be removed if the given item is not found

### ISSUE THREAD

**Issue by kodyfanz** [Bisonai/orakl#467]
In the `state.ts` files of `listener`, `reporter` and `worker` all seem to lack a check for the existence of the given item in active state. When the item is not found, `index` will be -1 and now the method `.splice(index,1)[0]` will return the last element of the array. To fix this issue, the code should check if the index is -1 before removing the item and throwing an error if it is.

**Comment by martinkersner** [comment]
Hello @kodyfanz

Thank you for raising the issue and creating solution for that. We are going to look into your PR soon!

Cheers,
Martin
