### ISSUE TITLE
implement new logic for RR multiple submissions in smart contracts

### ISSUE THREAD

**Issue by KelvinThai** [Bisonai/orakl#495]
+ Consumers will specify the number of submissions before fulfillment. This must be smaller than the total number of operators.
+ Operators will fulfill until reaching the number, the last one to submit will call the fulfill function.
+ The reward will be evenly distributed to all operators who submit the value.

**Comment by KelvinThai** [comment]
linked issue: https://github.com/Bisonai/orakl/issues/416

**Comment by martinkersner** [comment]
@KelvinThai Actually the last one should get more than the others because he has to spend gas on the fulfillment execution.

**Comment by KelvinThai** [comment]
aha! so the equation should be:
fee - fulfilment gas: evenly distributed
last submit operator will receive portion + fulfillment gas

**Comment by KelvinThai** [comment]
For the `chargeFee() function`. I suggest we split to: 
`ChargeFee()` : decrease accID balance
`payOperator()`: increase node balance

That way the Prepayment contract can be extendable for different services with different fee distribution calculations and distributions. Or If you have any better ideas, let me know

**Comment by martinkersner** [comment]
Thank you for the idea! 🚀 

I am currently touching on `Prepayment` and new contract called `Account`. I will try to share with you the latest version as soon as possible (the latest tomorrow). I have integrated there `protocolFee` as well. If it is possible can you ignore the payment for now. Then, we can see how it can all fit together.

**Comment by KelvinThai** [comment]
Perfect! let's catch up tomorrow.
