### ISSUE TITLE
separate  `reporter private key` from reporters table

### ISSUE THREAD

**Issue by bayram98** [Bisonai/orakl#577]
Currently, we set up `reporters` account with `privateKey` on the same table. It would be better if we could separate `privateKeys` out of table.

**Comment by martinkersner** [comment]
@bayram98 Can you be please more specific about this issue? I know we talked about related topic, but I don't think we need to make a new table 🤔

**Comment by KelvinThai** [comment]
We decided to store reported prv key in encrypted form
