### ISSUE TITLE
on the `Grafana` add new graph to visualize aggregator value from  `AggregatorProxy`

### ISSUE THREAD

**Issue by bayram98** [Bisonai/orakl#600]
This is just my proposal. 

Currently we only track the off-chain `fetched price` & `on-chain` submitted value of data feed. 

From the users perspective, users needs to call `aggregatorProxy` to read the data. I realize that if we had a any problem with proxy we couldn't see it easily from your current monitoring system. 

To improve coverage of our monitoring the system, I think we need to add the price table which read the aggregator value from the `AggregatorProxy` address.    

![Image](https://user-images.githubusercontent.com/30230748/236088497-da249940-4a9c-4f0e-9588-f0e1f94b9aa7.png)

**Comment by Intizar-T** [comment]
duplicate issue https://github.com/Bisonai/orakl/issues/1044
