### ISSUE TITLE
Define and deploy 11 new data feeds before the end of Q2.

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#608]
https://www.notion.so/bisonai/aee6a3e0d8b84131bacc350b4fa65242?v=6783ac6e93bd45dd9483df6a6c3497c8

* MNR/KRW (https://github.com/Bisonai/orakl/issues/601)
* Wemix
* Neopin
* Bora
* MBX

## Tentative Feeds

* ADA
* DOGE
* XRP
* SHIB

**Comment by KelvinThai** [comment]
Our datafeeds can be found here: https://github.com/Bisonai/data-feed-consumer
