### ISSUE TITLE
Investigate memory(RAM) leak on api cluster

### ISSUE THREAD

**Issue by bayram98** [Bisonai/orakl#846]

**Comment by martinkersner** [comment]
I think this is solved. Closing.

**Comment by martinkersner** [comment]
<img width="1635" alt="image" src="https://github.com/Bisonai/orakl/assets/2312761/7ad797cd-35fc-4a67-8a2e-47f1529a553c">

**Comment by jay-bisonai** [comment]
![Uploading Screenshot 2023-12-05 at 3.53.16 PM.png…]()
