### ISSUE TITLE
branching strategy suggestion

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#859]
## git flow

reference:
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
https://datasift.github.io/gitflow/IntroducingGitFlow.html
(korean) https://techblog.woowahan.com/2553/

we don't have to take full aspect of the strategy. but maybe just using `main(master)`, `dev`, and `feature` branch would be enough.

- main: branch for actual deployment
- dev: branch for the next version of the product
- feature: branch for development, could include new feature, bugfix, or anything

## why is it good

- compatible with concurrent and asynchronous development
- pull request size can be reduced since every pr doesn't have to be production ready, doesn't have to always run github actions

**Comment by Intizar-T** [comment]
The suggestion to add a `dev` branch can be very beneficial, especially in web or mobile applications. But given the nature of our product and the complexity of introducing a `dev` stage, it might be better to continue with the current structure.
