### ISSUE TITLE
allow feed modification

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#939]
To modify datafeed, as feeds are bond to adapter hash and aggregator hash it should be all removed and added

**Comment by martinkersner** [comment]
@Bisonai/orakl-team Off-chain aggregation does not utilize hash connection between adapter and aggregator. Once off-chain aggregation is deployed, it will be possible to modify feeds by updating orakl-config and restarting orakl node. Closing the issue.
